---
# tasks file for deploy-docker-boinc-boinctui
# Install necessary pip packages.
# See:
#   https://github.com/ansible/ansible/issues/20492#issuecomment-313325892
- name: Upgrade pip to the latest version.
  pip:
    name: pip
    state: latest

- name: Install docker-py and docker-compose pip packages.
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - docker-py
    - docker-compose

- name: Clean-up docker, docker-py, docker-compose pip packages.
  pip:
    name: "{{item}}"
    state: absent
  with_items:
    - docker
    - docker-py
    - docker-compose

- name: Install docker-py and docker-compose pip packages.
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - docker-compose

# copy systemd unit to /etc/systemd/system/
- name: Copy systemd unit file for BOINC client.
  template:
    src: ./templates/etc/systemd/system/docker-boinc.service.j2
    dest: /etc/systemd/system/docker-boinc.service
    mode: 0644

# enable service, reload systemd services, and restart docker-boinc service
- name: restart service docker-boinc
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: docker-boinc

# - name: Assert that container is running
#   assert:
#     that:
#       # access the json output produced in the last step
#       - ansible_facts["boinc"]["{{container_name}}"]["state"]["running"]

- name: Pull the image pataquets/boinctui:latest
  docker_image:
    name: pataquets/boinctui:latest

# copy files
- name: copying server.crt and ca.crt
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  loop:
    - {src: './files/usr/local/bin/boinc-htop',
       dest: '/usr/local/bin/boinc-htop',
       mode: 0775
       }
    - {src: './files/usr/local/bin/docker-boinctui',
       dest: '/usr/local/bin/docker-boinctui',
       mode: 0775
       }
    - {src: './files/usr/share/gotty-boinctui/docker-gotty-boinctui-systemd',
       dest: '/usr/share/gotty-boinctui/docker-gotty-boinctui-systemd',
       mode: 0775
       }
    - {src: './files/etc/systemd/system/gotty-boinctui.service',
       dest: '/etc/systemd/system/gotty-boinctui.service',
       mode: 0644
       }
    - {src: './files/etc/gotty-boinctui.conf',
       dest: '/etc/gotty-boinctui.conf',
       mode: 0644
       }
  become: true
