---
# tasks file for deploy-docker-boinc-boinctui
# Install necessary pip packages.
# See:
#   https://github.com/ansible/ansible/issues/20492#issuecomment-313325892
- name: Upgrade pip to the latest version.
  pip:
    name: pip
    state: latest

- name: Install docker-py and docker-compose pip packages.
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - docker-py
    - docker-compose

- name: Clean-up docker, docker-py, docker-compose pip packages.
  pip:
    name: "{{item}}"
    state: absent
  with_items:
    - docker
    - docker-py
    - docker-compose

- name: Install docker-py and docker-compose pip packages.
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - docker-compose

# Docker compose file with format inline v2
#
#   docker run --rm \
#              --hostname <boinc_client_hostname> \
#              --name boinc_client \
#              --volume boinc_data:/var/lib/boinc-client \
#              -e BOINC_GUI_RPC_PASSWORD=<boinc_gui_rpc_password> \
#                  boinc/client
#
- name: Run with inline v2 compose
  docker_service:
    project_name: boinc
    definition:
      boinc:
        container_name: boinc_client
        image: boinc/client
        hostname: "{{ boinc_client_hostname }}"
        volumes:
          - boinc_data:/var/lib/boinc-client
        restart: always
  register: docker_compose_output

- name: Assert that container is running
  assert:
    that:
      # access the json output produced in the last step
      - boinc.boinc_client.state.running

# copy systemd unit to /etc/systemd/system/
- name: Copy systemd unit file for BOINC client.
  template:
    src: ./templates/etc/systemd/system/docker-boinc-client.service.j2
    dest: /etc/systemd/system/docker-boinc-client.service
    mode: 0644

# enable service, reload systemd services, and
# restart docker-boinc-client service
# - name: restart docker-boinc-client service
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: docker-boinc-client
#     enabled: yes

- name: Pull the image pataquets/boinctui:latest
  docker_image:
    name: pataquets/boinctui:latest

# copy launch_docker-boinctui script to /usr/local/bin/
- name: Copy launch_docker-boinctui script to /usr/local/bin/
  copy:
    src: ./files/usr/local/bin/launch_docker-boinctui
    dest: /usr/local/bin/launch_docker-boinctui
    owner: root
    group: root
    mode: 0775

# copy boinc_htop script to /usr/local/bin/
- name: Copy boinc_htop script to /usr/local/bin/
  copy:
    src: ./files/usr/local/bin/boinc_htop
    dest: /usr/local/bin/boinc_htop
    owner: root
    group: root
    mode: 0775
