---
# tasks file for deploy-docker-boinc-boinctui
# Install necessary pip packages.
# See:
#   https://github.com/ansible/ansible/issues/20492#issuecomment-313325892
- name: Upgrade pip to the latest version.
  pip:
    name: pip
    state: latest

- name: Install docker-py and docker-compose pip packages.
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - docker-py
    - docker-compose

- name: Clean-up docker, docker-py, docker-compose pip packages.
  pip:
    name: "{{item}}"
    state: absent
  with_items:
    - docker
    - docker-py
    - docker-compose

- name: Install docker-py and docker-compose pip packages.
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - docker-compose

# Docker compose file with format inline v2
#
#   docker run --rm \
#              --hostname <hostaname>_dbc \
#              --name boinc_client \
#              -e BOINC_GUI_RPC_PASSWORD=<boinc_gui_rpc_password> \
#              --volume boinc_data:/var/lib/boinc \
#              --volume boinc_client_data:/var/lib/boinc-client \
#                  boinc/client
#
- name: Run with inline v2 compose
  docker_service:
    project_name: boinc
    definition:
      boinc:
        container_name: "{{container_name}}"
        image: boinc/client
        hostname: "{{container_hostname}}"
        volumes:
          - boinc_data:/var/lib/boinc
        restart: always
  register: docker_compose_output

- name: Assert that container is running
  assert:
    that:
      # access the json output produced in the last step
      - ansible_facts["boinc"]["{{container_name}}"]["state"]["running"]

# copy systemd unit to /etc/systemd/system/
- name: Copy systemd unit file for BOINC client.
  template:
    src: ./templates/etc/systemd/system/docker-boinc.service.j2
    dest: /etc/systemd/system/docker-boinc.service
    mode: 0644


# enable service, reload systemd services, and restart docker-boinc service
- name: restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: docker-boinc

- name: Pull the image pataquets/boinctui:latest
  docker_image:
    name: pataquets/boinctui:latest

# copy docker-boinctui script to /usr/local/bin/
- name: Copy docker-boinctui script to /usr/local/bin/
  copy:
    src: ./files/usr/local/bin/docker-boinctui
    dest: /usr/local/bin/docker-boinctui
    owner: root
    group: root
    mode: 0775

# copy boinc-htop script to /usr/local/bin/
- name: Copy boinc-htop script to /usr/local/bin/
  copy:
    src: ./files/usr/local/bin/boinc-htop
    dest: /usr/local/bin/boinc-htop
    owner: root
    group: root
    mode: 0775
