---
## Boinc variables

# role: 'add-user' (root)
update_root_password: true
root_groups: ['sudo']

# role: 'locales'
langs:
  - es_ES.UTF-8
  - en_US.UTF-8
  - it_IT.UTF-8

# role 'resize-boot-partition'
resized_boot_partition_size: '1GB'

# role 'set-hostname'
hostname: "{{ inventory_hostname }}"

# role: 'swap'
swapfile_size: 8G

# role 'ansible-docker'
# See also:
# https://github.com/nickjj/ansible-docker/issues/18
#
## Do you want to install Community Edition ('ce') or Enterprise Edition ('ee')?
docker_edition: "ce"

## Do you want to install Docker through the "stable" or "edge" channel?
## Stable gets updated every quarter and Edge gets updated every month.
docker_channel: "stable"

## What version of Docker do you want to install?
docker_version: "18.06.0"

# role: 'add-user'
boinc_user: 'boinc'
boinc_group: ['sudo', 'docker']
update_boinc_password: true

# role 'ssh-secure'
ssh_server_ports: ['22222']

# role 'set-ufw'
ufw_policy: 'deny'
ufw_logging: off
ufw_custom_ports:
  - {rule: limit, port: "{{ ssh_server_ports|join(',') }}", proto: tcp}

# role 'deploy-docker-boinc-boinctui'
container_hostname: "{{ inventory_hostname }}_dbc"
container_name: "boinc-client"
boinc_rpc_password: "boinc"
